name: update site

on: workflow_dispatch
env:
  CI: false

jobs:
  build:
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: |
          git clone https://github.com/behrenle/Math-Explorer.git
          git clone https://github.com/behrenle/behrenle.github.io.git
          echo node --version
          echo npm --version
          cd Math-Explorer
          npm install
          npm run build
          rm -rf ../behrenle.github.io/mathexplorer/*
          cp ./build/* ../behrenle.github.io/mathexplorer/*
          cd ../behrenle.github.io
          git config user.name "MATHEXPLORER_UPDATER"
          git config user.email "behrenle@posteo.de"
          git add -A
          git commit -am "updated MathExplorer"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          

