name: update-math-explorer

on:
  - workflow_dispatch
  - repository_dispatch

env:
  CI: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      
      - name: Build and commit updates
        run: |
          git clone https://github.com/behrenle/Math-Explorer.git
          git clone https://github.com/behrenle/behrenle.github.io.git
          cd Math-Explorer
          npm install
          npm run build
          cd ..
          rm -rf ./behrenle.github.io/mathexplorer
          mv ./Math-Explorer/build ./behrenle.github.io/mathexplorer
          cd ./behrenle.github.io
          git config --local user.name "MATH_EXPLORER_UPDATER"
          git config --local user.email "behrenle@posteo.de"
          git commit -am "updated MathExplorer"
          
      - name: Push changes to behrenle.github.io
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: ./behrenle.github.io
          

